# Generated by Django 4.1.7 on 2023-03-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25, verbose_name='Role')),
                ('user_id', models.CharField(max_length=25, verbose_name='User ID')),
                ('username', models.CharField(max_length=250, verbose_name='User ID')),
                ('text', models.TextField(max_length=10000, verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
