# Generated by Django 4.1.7 on 2023-03-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=25, verbose_name='Telegram user ID')),
                ('username', models.CharField(max_length=250, verbose_name='Username')),
                ('request', models.TextField(max_length=10000, verbose_name='Request')),
                ('response', models.TextField(max_length=10000, verbose_name='Response')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('completion_tokens', models.IntegerField(verbose_name='Completion tokens')),
                ('prompt_tokens', models.IntegerField(verbose_name='Prompt tokens')),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Texts',
            },
        ),
    ]
