# Generated by Django 4.1.7 on 2023-03-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='username',
            field=models.CharField(blank=True, max_length=250, verbose_name='Username'),
        ),
    ]
