# Generated by Django 4.2 on 2023-05-02 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='completion_tokens',
            field=models.IntegerField(blank=True, verbose_name='Completion tokens'),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='text',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, verbose_name='Prompt tokens'),
        ),
    ]
