# Generated by Django 4.1.7 on 2023-03-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25, verbose_name='Role')),
                ('user_id', models.CharField(max_length=25, verbose_name='User ID')),
                ('username', models.CharField(max_length=250, verbose_name='Username')),
                ('text', models.TextField(max_length=10000, verbose_name='Text')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
