# Generated by Django 4.1.7 on 2023-03-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_text_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='username',
            field=models.CharField(max_length=250, null=True, verbose_name='Username'),
        ),
    ]
