# Generated by Django 4.1.7 on 2023-03-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25, verbose_name='Role')),
                ('telegram_id', models.CharField(max_length=25, verbose_name='Telegram user ID')),
                ('username', models.CharField(max_length=250, verbose_name='Username')),
                ('text', models.TextField(max_length=10000, verbose_name='Text')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('tokens', models.IntegerField(verbose_name='Tokens')),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Texts',
            },
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='role',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='text',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='username',
        ),
    ]
