# Generated by Django 4.2 on 2023-05-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_text_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='total_tokens',
            field=models.IntegerField(null=True, verbose_name='Total tokens'),
        ),
    ]
