# Generated by Django 4.2 on 2023-05-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_text_total_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('img', 'Image')], default='text', max_length=4, verbose_name='Content Type'),
        ),
    ]
